# Generated by Django 4.1.2 on 2022-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='nullllll', max_length=64),
            preserve_default=False,
        ),
    ]
